from pathlib import Path
from typing import Literal, TypedDict

from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field

from ch_11_self_rag.nodes import Node, RouteVerdict
from ch_11_self_rag.step_1 import (
    decide_retrieval_node,
    generate_direct_node,
    llm,
    retrieve_node,
    route_after_decide,
)
from ch_11_self_rag.step_2 import is_relevant_node
from ch_11_self_rag.step_3 import (
    generate_from_context_node,
    no_relevant_docs_node,
    route_after_relevance,
)
from utils.logger import get_logger

logger = get_logger()

logger.info("Self RAG step_4 execution started.")


# State
class State(TypedDict):
    question: str
    answer: str
    need_retrieval: bool
    docs: list[Document]
    relevant_docs: list[Document]
    context: str

    # post generation verification
    is_supported: Literal["fully_supported", "partially_supported", "not_supported"]
    evidence: list[str]


# schema for is_supported_decision
class IsSupportedDecision(BaseModel):
    """Schema for the response generated by the llm to check if it is supported by the context"""

    is_supported: Literal["fully_supported", "partially_supported", "not_supported"]
    evidence: list[str] = Field(default_factory=list)


is_supported_prompt = ChatPromptTemplate.from_messages(
    messages=[
        (
            "system",
            """
                You're verifying whether the ANSWER is supported by the context.\n
                Return JSON with keys: is_supported, evidence\n
                is_supported must be one of: fully_supported, partially_supported, not_supported.\n
                How to decide is_supported:\n
                - fully_supported:\n
                    Every meaningful claim is explicitly supported by CONTEXT, and the ANSWER does NOT introduce\n
                    any qualitative/interpretive words that are not present in CONTEXT.\n
                    (Examples of disallowed words unless present in CONTEXT: culture, generous, robust, designed to,\n
                    supports professional development, best-in-class, employee-first, etc.)\n\n
                - partially_supported:\n
                    The core facts are supported, BUT the ANSWER includes ANY abstraction, interpretation, or qualitative\n
                    phrasing not explicitly stated in CONTEXT (e.g., calling policies 'culture', saying leave is 'generous',\n
                    or inferring outcomes like 'supports professional development').\n\n
                - no_support:\n
                    The key claims are not supported by CONTEXT.\n\n
                Rules:\n
                    - Be strict: if you see ANY unsupported qualitative/interpretive phrasing, choose partially_supported.\n
                    - If the answer is mostly unrelated to the question or unsupported, choose no_support.\n
                    - Evidence: include up to 3 short direct quotes from CONTEXT that support the supported parts.\n
                    - Do not use outside knowledge."
            """,
        ),
        ("human", """Question: {question}\nAnswer: {answer}\nContext: {context}"""),
    ]
)

is_supported_llm = llm.with_structured_output(schema=IsSupportedDecision)


def is_supported_node(state: State) -> State:
    logger.info(
        "Checking if the response generated by llm is supported by context or not."
    )
    decision: IsSupportedDecision = is_supported_llm.invoke(
        is_supported_prompt.format_messages(
            question=state.get("question"),
            answer=state.get("answer"),
            context=state.get("context"),
        )
    )
    return {"is_supported": decision.is_supported}


# define graph
graph = StateGraph(state_schema=State)

# add nodes
graph.add_node(Node.DECIDE_RETRIEVAL, decide_retrieval_node)
graph.add_node(Node.GENERATE_DIRECT, generate_direct_node)
graph.add_node(Node.RETRIEVE, retrieve_node)
graph.add_node(Node.IS_RELEVANT, is_relevant_node)
graph.add_node(Node.GENERATE_FROM_CONTEXT, generate_from_context_node)
graph.add_node(Node.NO_RELEVANT_DOCS, no_relevant_docs_node)
graph.add_node(Node.IS_SUPPORTED, is_supported_node)

# add edges
graph.add_edge(START, Node.DECIDE_RETRIEVAL)
graph.add_conditional_edges(
    source=Node.DECIDE_RETRIEVAL,
    path=route_after_decide,
    path_map={
        RouteVerdict.DIRECT: Node.GENERATE_DIRECT,
        RouteVerdict.RETRIEVE: Node.RETRIEVE,
    },
)
graph.add_edge(Node.GENERATE_DIRECT, END)
graph.add_edge(Node.RETRIEVE, Node.IS_RELEVANT)
graph.add_conditional_edges(
    source=Node.IS_RELEVANT,
    path=route_after_relevance,
    path_map={
        RouteVerdict.GENERATE_FROM_CONTEXT: Node.GENERATE_FROM_CONTEXT,
        RouteVerdict.NO_RELEVANT_DOCS: Node.NO_RELEVANT_DOCS,
    },
)
graph.add_edge(Node.NO_RELEVANT_DOCS, END)
graph.add_edge(Node.GENERATE_FROM_CONTEXT, Node.IS_SUPPORTED)
graph.add_edge(Node.IS_SUPPORTED, END)

# compile graph
app = graph.compile()

if __name__ == "__main__":
    # Generates and writes the graph image directly to your project root / graphs
    png_data = app.get_graph().draw_mermaid_png()
    Path("graphs/self_rag_4.png").write_bytes(png_data)
    logger.info("Graph saved to root directory")

    result: State = app.invoke({"question": "Who is the CEO of Nexa AI?"})

    logger.info(f"Need retrieval? : {result['need_retrieval']}")

    logger.info(f"Qustion: {result.get('question')}")

    if "answer" in result and result.get("context") == "":
        logger.info(f"{result['answer']}")
    else:
        logger.info(f"{result['answer'][0]['text']}")

    logger.info(f"Docs: {result.get('docs')}")
    logger.info(f"Relevant docs: {result.get('relevant_docs')}")
    logger.info(f"Context: {result.get('context')}")
    logger.info(f"Is supported: {result.get('is_supported')}")
    logger.info(f"Evidence: {result.get('evidence')}")
